# Generated by ../generate_metasyntax.py
from goto import with_goto
import re

import ast
import textwrap


class Node:
    _fields = ()

    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        for field in self._fields:
            if getattr(self, field) != getattr(other, field):
                return False
        return True

    def _asdict(self):
        return {k: getattr(self, k) for k in self._fields}

    def _replace(self, **kw):
        for field in self._fields:
            if field not in kw:
                kw[field] = getattr(self, field)
        return self.__class__(**kw)

_pattern1 = re.compile('[ \\t]+')
_pattern2 = re.compile('#[^\\r\\n]*')
_pattern3 = re.compile('[\\r\\n][\\s]*')
_pattern4 = re.compile('[_a-zA-Z][_a-zA-Z0-9]*')

class StringLiteral(Node):
    _fields = ('value',)

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return f'StringLiteral(value={self.value!r})'

_pattern5 = re.compile('(?s)("""([^\\\\]|\\\\.)*?""")')
_pattern6 = re.compile("(?s)('''([^\\\\]|\\\\.)*?''')")
_pattern7 = re.compile('("([^"\\\\]|\\\\.)*")')
_pattern8 = re.compile("('([^'\\\\]|\\\\.)*')")

class RegexLiteral(Node):
    _fields = ('value',)

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return f'RegexLiteral(value={self.value!r})'

_pattern9 = re.compile('\\@\\/([^\\/\\\\]|\\\\.)*\\/')

class PythonSection(Node):
    _fields = ('value',)

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return f'PythonSection(value={self.value!r})'

_pattern10 = re.compile('(?s)```.*?```')

class PythonExpression(Node):
    _fields = ('value',)

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return f'PythonExpression(value={self.value!r})'

_pattern11 = re.compile('`.*?`')

class RuleDef(Node):
    _fields = ('is_ignored', 'name', 'expr')

    def __init__(self, is_ignored, name, expr):
        self.is_ignored = is_ignored
        self.name = name
        self.expr = expr

    def __repr__(self):
        return f'RuleDef(is_ignored={self.is_ignored!r}, name={self.name!r}, expr={self.expr!r})'


class ClassDef(Node):
    _fields = ('name', 'fields')

    def __init__(self, name, fields):
        self.name = name
        self.fields = fields

    def __repr__(self):
        return f'ClassDef(name={self.name!r}, fields={self.fields!r})'


class TemplateDef(Node):
    _fields = ('name', 'params', 'expr')

    def __init__(self, name, params, expr):
        self.name = name
        self.params = params
        self.expr = expr

    def __repr__(self):
        return f'TemplateDef(name={self.name!r}, params={self.params!r}, expr={self.expr!r})'


class Ref(Node):
    _fields = ('value',)

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return f'Ref(value={self.value!r})'


class ListLiteral(Node):
    _fields = ('elements',)

    def __init__(self, elements):
        self.elements = elements

    def __repr__(self):
        return f'ListLiteral(elements={self.elements!r})'


class KeywordArg(Node):
    _fields = ('name', 'expr')

    def __init__(self, name, expr):
        self.name = name
        self.expr = expr

    def __repr__(self):
        return f'KeywordArg(name={self.name!r}, expr={self.expr!r})'


class ArgList(Node):
    _fields = ('args',)

    def __init__(self, args):
        self.args = args

    def __repr__(self):
        return f'ArgList(args={self.args!r})'


class ParseError(Exception):
    def __init__(self, expr_code, pos):
        self.expr_code = expr_code
        self.pos = pos



class Infix(Node):
    _fields = ('left', 'operator', 'right')

    def __init__(self, left, operator, right):
        self.left = left
        self.operator = operator
        self.right = right

    def __repr__(self):
        return f'Infix({self.left!r}, {self.operator!r}, {self.right!r})'


class Postfix(Node):
    _fields = ('left', 'operator')

    def __init__(self, left, operator):
        self.left = left
        self.operator = operator

    def __repr__(self):
        return f'Postfix({self.left!r}, {self.operator!r})'


class Prefix(Node):
    _fields = ('operator', 'right')

    def __init__(self, operator, right):
        self.operator = operator
        self.right = right

    def __repr__(self):
        return f'Prefix({self.operator!r}, {self.right!r})'


def parse(text, pos=0):
    return _run(text, pos, _skip_then_start)


def _run(text, pos, start):
    memo = {}
    result = None

    key = (3, start, pos)
    gtor = start(text, pos)
    stack = [(key, gtor)]

    while stack:
        key, gtor = stack[-1]
        result = gtor.send(result)

        if result[0] != 3:
            stack.pop()
            memo[key] = result
        elif result in memo:
            result = memo[result]
        else:
            gtor = result[1](text, result[2])
            stack.append((result, gtor))
            result = None

    if result[0]:
        return result[1]
    else:
        raise ParseError(result[1], result[2])


def visit(node):
    if isinstance(node, list):
        yield from node

    elif isinstance(node, Node):
        yield node

        if hasattr(node, '_fields'):
            for field in node._fields:
                yield from visit(getattr(node, field))


def transform(node, *callbacks):
    if not callbacks:
        return node

    if len(callbacks) == 1:
        callback = callbacks[0]
    else:
        def callback(node):
            for f in callbacks:
                node = f(node)
            return node

    return _transform(node, callback)


def _transform(node, callback):
    if isinstance(node, list):
        return [_transform(x, callback) for x in node]

    if not isinstance(node, Node):
        return node

    updates = {}
    for field in node._fields:
        was = getattr(node, field)
        now = _transform(was, callback)
        if was is not now:
            updates[field] = now

    if updates:
        node = node._replace(**updates)

    return callback(node)


@with_goto
def _parse_Space1(_text, _pos):
    _match1 = _pattern1.match(_text, _pos)
    if _match1:
        _pos = _match1.end()
        _checkpoint1 = _pos
        label ._loop_skip1
        _match2 = _pattern1.match(_text, _pos)
        if _match2:
            _pos = _match2.end()
            _mode = True
            _result = _match2.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint1 = _pos
            goto ._loop_skip1
        _match3 = _pattern2.match(_text, _pos)
        if _match3:
            _pos = _match3.end()
            _mode = True
            _result = _match3.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint1 = _pos
            goto ._loop_skip1
        _mode = True
        _result = None
        _pos = _checkpoint1
        _mode = True
        _result = _match1.group(0)
    else:
        _mode = False
        _result = 139639492039624
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Comment1(_text, _pos):
    _match4 = _pattern2.match(_text, _pos)
    if _match4:
        _pos = _match4.end()
        _checkpoint2 = _pos
        label ._loop_skip2
        _match5 = _pattern1.match(_text, _pos)
        if _match5:
            _pos = _match5.end()
            _mode = True
            _result = _match5.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint2 = _pos
            goto ._loop_skip2
        _match6 = _pattern2.match(_text, _pos)
        if _match6:
            _pos = _match6.end()
            _mode = True
            _result = _match6.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint2 = _pos
            goto ._loop_skip2
        _mode = True
        _result = None
        _pos = _checkpoint2
        _mode = True
        _result = _match4.group(0)
    else:
        _mode = False
        _result = 139639492005280
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Newline1(_text, _pos):
    _match7 = _pattern3.match(_text, _pos)
    if _match7:
        _pos = _match7.end()
        _checkpoint3 = _pos
        label ._loop_skip3
        _match8 = _pattern1.match(_text, _pos)
        if _match8:
            _pos = _match8.end()
            _mode = True
            _result = _match8.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint3 = _pos
            goto ._loop_skip3
        _match9 = _pattern2.match(_text, _pos)
        if _match9:
            _pos = _match9.end()
            _mode = True
            _result = _match9.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint3 = _pos
            goto ._loop_skip3
        _mode = True
        _result = None
        _pos = _checkpoint3
        _mode = True
        _result = _match7.group(0)
    else:
        _mode = False
        _result = 139639492004440
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Sep1(_text, _pos):
    _staging1 = []
    label ._loop_list1
    _checkpoint4 = _pos
    _backtrack1 = _pos
    _farthest_pos1 = _pos
    _farthest_expr1 = 139639492127600
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        goto ._end_choice1
    if _farthest_pos1 < _pos:
        _farthest_pos1 = _pos
        _farthest_expr1 = 139639492002648
    _pos = _backtrack1
    _value1 = ';'
    _end1 = _pos + 1
    if _text[_pos:_end1] == _value1:
        _pos = _end1
        _checkpoint5 = _pos
        label ._loop_skip4
        _match10 = _pattern1.match(_text, _pos)
        if _match10:
            _pos = _match10.end()
            _mode = True
            _result = _match10.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint5 = _pos
            goto ._loop_skip4
        _match11 = _pattern2.match(_text, _pos)
        if _match11:
            _pos = _match11.end()
            _mode = True
            _result = _match11.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint5 = _pos
            goto ._loop_skip4
        _mode = True
        _result = None
        _pos = _checkpoint5
        _mode = True
        _result = _value1
    else:
        _mode = False
        _result = 139639491956632
    if _mode:
        goto ._end_choice1
    if _farthest_pos1 < _pos:
        _farthest_pos1 = _pos
        _farthest_expr1 = 139639491956632
    _pos = _backtrack1
    _result = _farthest_expr1
    _pos = _farthest_pos1
    label ._end_choice1
    if _mode:
        _staging1.append(_result)
        goto ._loop_list1
    else:
        _pos = _checkpoint4
        goto ._end_list1
    label ._end_list1
    if _staging1:
        _mode = True
        _result = _staging1
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Name1(_text, _pos):
    _match12 = _pattern4.match(_text, _pos)
    if _match12:
        _pos = _match12.end()
        _checkpoint6 = _pos
        label ._loop_skip5
        _match13 = _pattern1.match(_text, _pos)
        if _match13:
            _pos = _match13.end()
            _mode = True
            _result = _match13.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint6 = _pos
            goto ._loop_skip5
        _match14 = _pattern2.match(_text, _pos)
        if _match14:
            _pos = _match14.end()
            _mode = True
            _result = _match14.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint6 = _pos
            goto ._loop_skip5
        _mode = True
        _result = None
        _pos = _checkpoint6
        _mode = True
        _result = _match12.group(0)
    else:
        _mode = False
        _result = 139639492003936
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Comma1(_text, _pos):
    _checkpoint7 = _pos
    label ._loop_skip6
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint7 = _pos
        goto ._loop_skip6
    _mode = True
    _result = None
    _pos = _checkpoint7
    if not _mode:
        goto ._end_discard1
    _value2 = ','
    _end2 = _pos + 1
    if _text[_pos:_end2] == _value2:
        _pos = _end2
        _checkpoint8 = _pos
        label ._loop_skip7
        _match15 = _pattern1.match(_text, _pos)
        if _match15:
            _pos = _match15.end()
            _mode = True
            _result = _match15.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint8 = _pos
            goto ._loop_skip7
        _match16 = _pattern2.match(_text, _pos)
        if _match16:
            _pos = _match16.end()
            _mode = True
            _result = _match16.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint8 = _pos
            goto ._loop_skip7
        _mode = True
        _result = None
        _pos = _checkpoint8
        _mode = True
        _result = _value2
    else:
        _mode = False
        _result = 139639491955680
    label ._end_discard1
    if not _mode:
        goto ._end_discard2
    _staging2 = _result
    _checkpoint9 = _pos
    label ._loop_skip8
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint9 = _pos
        goto ._loop_skip8
    _mode = True
    _result = None
    _pos = _checkpoint9
    if _mode:
        _result = _staging2
    label ._end_discard2
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_StringLiteral1(_text, _pos):
    _backtrack2 = _pos
    _farthest_pos2 = _pos
    _farthest_expr2 = 139639492128608
    _match17 = _pattern5.match(_text, _pos)
    if _match17:
        _pos = _match17.end()
        _checkpoint10 = _pos
        label ._loop_skip9
        _match18 = _pattern1.match(_text, _pos)
        if _match18:
            _pos = _match18.end()
            _mode = True
            _result = _match18.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint10 = _pos
            goto ._loop_skip9
        _match19 = _pattern2.match(_text, _pos)
        if _match19:
            _pos = _match19.end()
            _mode = True
            _result = _match19.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint10 = _pos
            goto ._loop_skip9
        _mode = True
        _result = None
        _pos = _checkpoint10
        _mode = True
        _result = _match17.group(0)
    else:
        _mode = False
        _result = 139639492648688
    if _mode:
        goto ._end_choice2
    if _farthest_pos2 < _pos:
        _farthest_pos2 = _pos
        _farthest_expr2 = 139639492648688
    _pos = _backtrack2
    _match20 = _pattern6.match(_text, _pos)
    if _match20:
        _pos = _match20.end()
        _checkpoint11 = _pos
        label ._loop_skip10
        _match21 = _pattern1.match(_text, _pos)
        if _match21:
            _pos = _match21.end()
            _mode = True
            _result = _match21.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint11 = _pos
            goto ._loop_skip10
        _match22 = _pattern2.match(_text, _pos)
        if _match22:
            _pos = _match22.end()
            _mode = True
            _result = _match22.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint11 = _pos
            goto ._loop_skip10
        _mode = True
        _result = None
        _pos = _checkpoint11
        _mode = True
        _result = _match20.group(0)
    else:
        _mode = False
        _result = 139639492648184
    if _mode:
        goto ._end_choice2
    if _farthest_pos2 < _pos:
        _farthest_pos2 = _pos
        _farthest_expr2 = 139639492648184
    _pos = _backtrack2
    _match23 = _pattern7.match(_text, _pos)
    if _match23:
        _pos = _match23.end()
        _checkpoint12 = _pos
        label ._loop_skip11
        _match24 = _pattern1.match(_text, _pos)
        if _match24:
            _pos = _match24.end()
            _mode = True
            _result = _match24.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint12 = _pos
            goto ._loop_skip11
        _match25 = _pattern2.match(_text, _pos)
        if _match25:
            _pos = _match25.end()
            _mode = True
            _result = _match25.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint12 = _pos
            goto ._loop_skip11
        _mode = True
        _result = None
        _pos = _checkpoint12
        _mode = True
        _result = _match23.group(0)
    else:
        _mode = False
        _result = 139639492648800
    if _mode:
        goto ._end_choice2
    if _farthest_pos2 < _pos:
        _farthest_pos2 = _pos
        _farthest_expr2 = 139639492648800
    _pos = _backtrack2
    _match26 = _pattern8.match(_text, _pos)
    if _match26:
        _pos = _match26.end()
        _checkpoint13 = _pos
        label ._loop_skip12
        _match27 = _pattern1.match(_text, _pos)
        if _match27:
            _pos = _match27.end()
            _mode = True
            _result = _match27.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint13 = _pos
            goto ._loop_skip12
        _match28 = _pattern2.match(_text, _pos)
        if _match28:
            _pos = _match28.end()
            _mode = True
            _result = _match28.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint13 = _pos
            goto ._loop_skip12
        _mode = True
        _result = None
        _pos = _checkpoint13
        _mode = True
        _result = _match26.group(0)
    else:
        _mode = False
        _result = 139639492682080
    if _mode:
        goto ._end_choice2
    if _farthest_pos2 < _pos:
        _farthest_pos2 = _pos
        _farthest_expr2 = 139639492682080
    _pos = _backtrack2
    _result = _farthest_expr2
    _pos = _farthest_pos2
    label ._end_choice2
    if not _mode:
        goto ._end_apply1
    __item1 = _result
    _mode = True
    _result = ast.literal_eval
    if _mode:
        _result = _result(__item1)
    label ._end_apply1
    if not _mode:
        goto ._end_sequence1
    _item1 = _result
    _result = StringLiteral(_item1)
    label ._end_sequence1
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_RegexLiteral1(_text, _pos):
    _match29 = _pattern9.match(_text, _pos)
    if _match29:
        _pos = _match29.end()
        _checkpoint14 = _pos
        label ._loop_skip13
        _match30 = _pattern1.match(_text, _pos)
        if _match30:
            _pos = _match30.end()
            _mode = True
            _result = _match30.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint14 = _pos
            goto ._loop_skip13
        _match31 = _pattern2.match(_text, _pos)
        if _match31:
            _pos = _match31.end()
            _mode = True
            _result = _match31.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint14 = _pos
            goto ._loop_skip13
        _mode = True
        _result = None
        _pos = _checkpoint14
        _mode = True
        _result = _match29.group(0)
    else:
        _mode = False
        _result = 139639492646896
    if not _mode:
        goto ._end_apply2
    __item2 = _result
    _mode = True
    _result = lambda x: x[2:-1]
    if _mode:
        _result = _result(__item2)
    label ._end_apply2
    if not _mode:
        goto ._end_sequence2
    _item2 = _result
    _result = RegexLiteral(_item2)
    label ._end_sequence2
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_PythonSection1(_text, _pos):
    _match32 = _pattern10.match(_text, _pos)
    if _match32:
        _pos = _match32.end()
        _checkpoint15 = _pos
        label ._loop_skip14
        _match33 = _pattern1.match(_text, _pos)
        if _match33:
            _pos = _match33.end()
            _mode = True
            _result = _match33.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint15 = _pos
            goto ._loop_skip14
        _match34 = _pattern2.match(_text, _pos)
        if _match34:
            _pos = _match34.end()
            _mode = True
            _result = _match34.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint15 = _pos
            goto ._loop_skip14
        _mode = True
        _result = None
        _pos = _checkpoint15
        _mode = True
        _result = _match32.group(0)
    else:
        _mode = False
        _result = 139639502857440
    if not _mode:
        goto ._end_apply3
    __item3 = _result
    _mode = True
    _result = lambda x: textwrap.dedent(x[3:-3])
    if _mode:
        _result = _result(__item3)
    label ._end_apply3
    if not _mode:
        goto ._end_sequence3
    _item3 = _result
    _result = PythonSection(_item3)
    label ._end_sequence3
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_PythonExpression1(_text, _pos):
    _match35 = _pattern11.match(_text, _pos)
    if _match35:
        _pos = _match35.end()
        _checkpoint16 = _pos
        label ._loop_skip15
        _match36 = _pattern1.match(_text, _pos)
        if _match36:
            _pos = _match36.end()
            _mode = True
            _result = _match36.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint16 = _pos
            goto ._loop_skip15
        _match37 = _pattern2.match(_text, _pos)
        if _match37:
            _pos = _match37.end()
            _mode = True
            _result = _match37.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint16 = _pos
            goto ._loop_skip15
        _mode = True
        _result = None
        _pos = _checkpoint16
        _mode = True
        _result = _match35.group(0)
    else:
        _mode = False
        _result = 139639492089616
    if not _mode:
        goto ._end_apply4
    __item4 = _result
    _mode = True
    _result = lambda x: x[1:-1]
    if _mode:
        _result = _result(__item4)
    label ._end_apply4
    if not _mode:
        goto ._end_sequence4
    _item4 = _result
    _result = PythonExpression(_item4)
    label ._end_sequence4
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_RuleDef1(_text, _pos):
    _backtrack3 = _pos
    _backtrack4 = _pos
    _farthest_pos3 = _pos
    _farthest_expr3 = 139639492137704
    _value3 = 'ignored'
    _end3 = _pos + 7
    if _text[_pos:_end3] == _value3:
        _pos = _end3
        _checkpoint17 = _pos
        label ._loop_skip16
        _match38 = _pattern1.match(_text, _pos)
        if _match38:
            _pos = _match38.end()
            _mode = True
            _result = _match38.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint17 = _pos
            goto ._loop_skip16
        _match39 = _pattern2.match(_text, _pos)
        if _match39:
            _pos = _match39.end()
            _mode = True
            _result = _match39.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint17 = _pos
            goto ._loop_skip16
        _mode = True
        _result = None
        _pos = _checkpoint17
        _mode = True
        _result = _value3
    else:
        _mode = False
        _result = 139639492090232
    if _mode:
        goto ._end_choice3
    if _farthest_pos3 < _pos:
        _farthest_pos3 = _pos
        _farthest_expr3 = 139639492090232
    _pos = _backtrack4
    _value4 = 'ignore'
    _end4 = _pos + 6
    if _text[_pos:_end4] == _value4:
        _pos = _end4
        _checkpoint18 = _pos
        label ._loop_skip17
        _match40 = _pattern1.match(_text, _pos)
        if _match40:
            _pos = _match40.end()
            _mode = True
            _result = _match40.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint18 = _pos
            goto ._loop_skip17
        _match41 = _pattern2.match(_text, _pos)
        if _match41:
            _pos = _match41.end()
            _mode = True
            _result = _match41.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint18 = _pos
            goto ._loop_skip17
        _mode = True
        _result = None
        _pos = _checkpoint18
        _mode = True
        _result = _value4
    else:
        _mode = False
        _result = 139639492090288
    if _mode:
        goto ._end_choice3
    if _farthest_pos3 < _pos:
        _farthest_pos3 = _pos
        _farthest_expr3 = 139639492090288
    _pos = _backtrack4
    _result = _farthest_expr3
    _pos = _farthest_pos3
    label ._end_choice3
    if not _mode:
        _mode = True
        _result = None
        _pos = _backtrack3
    if not _mode:
        goto ._end_apply5
    __item5 = _result
    _mode = True
    _result = bool
    if _mode:
        _result = _result(__item5)
    label ._end_apply5
    if not _mode:
        goto ._end_sequence5
    _item5 = _result
    _mode, _result, _pos = yield (3, _parse_Name1, _pos)
    if not _mode:
        goto ._end_discard3
    _staging3 = _result
    _backtrack5 = _pos
    _farthest_pos4 = _pos
    _farthest_expr4 = 139639492137928
    _value5 = '='
    _end5 = _pos + 1
    if _text[_pos:_end5] == _value5:
        _pos = _end5
        _checkpoint19 = _pos
        label ._loop_skip18
        _match42 = _pattern1.match(_text, _pos)
        if _match42:
            _pos = _match42.end()
            _mode = True
            _result = _match42.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint19 = _pos
            goto ._loop_skip18
        _match43 = _pattern2.match(_text, _pos)
        if _match43:
            _pos = _match43.end()
            _mode = True
            _result = _match43.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint19 = _pos
            goto ._loop_skip18
        _mode = True
        _result = None
        _pos = _checkpoint19
        _mode = True
        _result = _value5
    else:
        _mode = False
        _result = 139639492090512
    if _mode:
        goto ._end_choice4
    if _farthest_pos4 < _pos:
        _farthest_pos4 = _pos
        _farthest_expr4 = 139639492090512
    _pos = _backtrack5
    _value6 = ':'
    _end6 = _pos + 1
    if _text[_pos:_end6] == _value6:
        _pos = _end6
        _checkpoint20 = _pos
        label ._loop_skip19
        _match44 = _pattern1.match(_text, _pos)
        if _match44:
            _pos = _match44.end()
            _mode = True
            _result = _match44.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint20 = _pos
            goto ._loop_skip19
        _match45 = _pattern2.match(_text, _pos)
        if _match45:
            _pos = _match45.end()
            _mode = True
            _result = _match45.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint20 = _pos
            goto ._loop_skip19
        _mode = True
        _result = None
        _pos = _checkpoint20
        _mode = True
        _result = _value6
    else:
        _mode = False
        _result = 139639492090568
    if _mode:
        goto ._end_choice4
    if _farthest_pos4 < _pos:
        _farthest_pos4 = _pos
        _farthest_expr4 = 139639492090568
    _pos = _backtrack5
    _result = _farthest_expr4
    _pos = _farthest_pos4
    label ._end_choice4
    if _mode:
        _result = _staging3
    label ._end_discard3
    if not _mode:
        goto ._end_sequence5
    _item6 = _result
    _mode, _result, _pos = yield (3, _parse_Expr1, _pos)
    if not _mode:
        goto ._end_sequence5
    _item7 = _result
    _result = RuleDef(_item5, _item6, _item7)
    label ._end_sequence5
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_ClassDef1(_text, _pos):
    _value7 = 'class'
    _end7 = _pos + 5
    if _text[_pos:_end7] == _value7:
        _pos = _end7
        _checkpoint21 = _pos
        label ._loop_skip20
        _match46 = _pattern1.match(_text, _pos)
        if _match46:
            _pos = _match46.end()
            _mode = True
            _result = _match46.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint21 = _pos
            goto ._loop_skip20
        _match47 = _pattern2.match(_text, _pos)
        if _match47:
            _pos = _match47.end()
            _mode = True
            _result = _match47.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint21 = _pos
            goto ._loop_skip20
        _mode = True
        _result = None
        _pos = _checkpoint21
        _mode = True
        _result = _value7
    else:
        _mode = False
        _result = 139639492091128
    if not _mode:
        goto ._end_discard4
    _mode, _result, _pos = yield (3, _parse_Name1, _pos)
    label ._end_discard4
    if not _mode:
        goto ._end_sequence6
    _item8 = _result
    _checkpoint22 = _pos
    label ._loop_skip21
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint22 = _pos
        goto ._loop_skip21
    _mode = True
    _result = None
    _pos = _checkpoint22
    if not _mode:
        goto ._end_discard5
    _value8 = '{'
    _end8 = _pos + 1
    if _text[_pos:_end8] == _value8:
        _pos = _end8
        _checkpoint23 = _pos
        label ._loop_skip22
        _match48 = _pattern1.match(_text, _pos)
        if _match48:
            _pos = _match48.end()
            _mode = True
            _result = _match48.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint23 = _pos
            goto ._loop_skip22
        _match49 = _pattern2.match(_text, _pos)
        if _match49:
            _pos = _match49.end()
            _mode = True
            _result = _match49.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint23 = _pos
            goto ._loop_skip22
        _mode = True
        _result = None
        _pos = _checkpoint23
        _mode = True
        _result = _value8
    else:
        _mode = False
        _result = 139639492091520
    label ._end_discard5
    if not _mode:
        goto ._end_discard6
    _staging4 = _result
    _checkpoint24 = _pos
    label ._loop_skip23
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint24 = _pos
        goto ._loop_skip23
    _mode = True
    _result = None
    _pos = _checkpoint24
    if _mode:
        _result = _staging4
    label ._end_discard6
    if not _mode:
        goto ._end_discard7
    _staging5 = []
    _checkpoint25 = _pos
    label ._loop_alt1
    _mode, _result, _pos = yield (3, _parse_RuleDef1, _pos)
    if not _mode:
        goto ._end_alt1
    _staging5.append(_result)
    _checkpoint25 = _pos
    _mode, _result, _pos = yield (3, _parse_Sep1, _pos)
    if not _mode:
        goto ._end_alt1
    _checkpoint25 = _pos
    goto ._loop_alt1
    label ._end_alt1
    _mode = True
    _result = _staging5
    _pos = _checkpoint25
    label ._end_discard7
    if not _mode:
        goto ._end_discard8
    _staging6 = _result
    _value9 = '}'
    _end9 = _pos + 1
    if _text[_pos:_end9] == _value9:
        _pos = _end9
        _checkpoint26 = _pos
        label ._loop_skip24
        _match50 = _pattern1.match(_text, _pos)
        if _match50:
            _pos = _match50.end()
            _mode = True
            _result = _match50.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint26 = _pos
            goto ._loop_skip24
        _match51 = _pattern2.match(_text, _pos)
        if _match51:
            _pos = _match51.end()
            _mode = True
            _result = _match51.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint26 = _pos
            goto ._loop_skip24
        _mode = True
        _result = None
        _pos = _checkpoint26
        _mode = True
        _result = _value9
    else:
        _mode = False
        _result = 139639492091240
    if _mode:
        _result = _staging6
    label ._end_discard8
    if not _mode:
        goto ._end_sequence6
    _item9 = _result
    _result = ClassDef(_item8, _item9)
    label ._end_sequence6
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_TemplateDef1(_text, _pos):
    _value10 = 'template'
    _end10 = _pos + 8
    if _text[_pos:_end10] == _value10:
        _pos = _end10
        _checkpoint27 = _pos
        label ._loop_skip25
        _match52 = _pattern1.match(_text, _pos)
        if _match52:
            _pos = _match52.end()
            _mode = True
            _result = _match52.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint27 = _pos
            goto ._loop_skip25
        _match53 = _pattern2.match(_text, _pos)
        if _match53:
            _pos = _match53.end()
            _mode = True
            _result = _match53.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint27 = _pos
            goto ._loop_skip25
        _mode = True
        _result = None
        _pos = _checkpoint27
        _mode = True
        _result = _value10
    else:
        _mode = False
        _result = 139639492161776
    if not _mode:
        goto ._end_discard9
    _mode, _result, _pos = yield (3, _parse_Name1, _pos)
    label ._end_discard9
    if not _mode:
        goto ._end_sequence7
    _item10 = _result
    _checkpoint28 = _pos
    label ._loop_skip26
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint28 = _pos
        goto ._loop_skip26
    _mode = True
    _result = None
    _pos = _checkpoint28
    if not _mode:
        goto ._end_discard10
    _value11 = '('
    _end11 = _pos + 1
    if _text[_pos:_end11] == _value11:
        _pos = _end11
        _checkpoint29 = _pos
        label ._loop_skip27
        _match54 = _pattern1.match(_text, _pos)
        if _match54:
            _pos = _match54.end()
            _mode = True
            _result = _match54.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint29 = _pos
            goto ._loop_skip27
        _match55 = _pattern2.match(_text, _pos)
        if _match55:
            _pos = _match55.end()
            _mode = True
            _result = _match55.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint29 = _pos
            goto ._loop_skip27
        _mode = True
        _result = None
        _pos = _checkpoint29
        _mode = True
        _result = _value11
    else:
        _mode = False
        _result = 139639492162168
    label ._end_discard10
    if not _mode:
        goto ._end_discard11
    _staging7 = _result
    _checkpoint30 = _pos
    label ._loop_skip28
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint30 = _pos
        goto ._loop_skip28
    _mode = True
    _result = None
    _pos = _checkpoint30
    if _mode:
        _result = _staging7
    label ._end_discard11
    if not _mode:
        goto ._end_discard12
    _staging8 = []
    _checkpoint31 = _pos
    label ._loop_alt2
    _checkpoint32 = _pos
    label ._loop_skip29
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint32 = _pos
        goto ._loop_skip29
    _mode = True
    _result = None
    _pos = _checkpoint32
    if not _mode:
        goto ._end_discard13
    _mode, _result, _pos = yield (3, _parse_Name1, _pos)
    label ._end_discard13
    if not _mode:
        goto ._end_discard14
    _staging9 = _result
    _checkpoint33 = _pos
    label ._loop_skip30
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint33 = _pos
        goto ._loop_skip30
    _mode = True
    _result = None
    _pos = _checkpoint33
    if _mode:
        _result = _staging9
    label ._end_discard14
    if not _mode:
        goto ._end_alt2
    _staging8.append(_result)
    _checkpoint31 = _pos
    _mode, _result, _pos = yield (3, _parse_Comma1, _pos)
    if not _mode:
        goto ._end_alt2
    _checkpoint31 = _pos
    goto ._loop_alt2
    label ._end_alt2
    _mode = True
    _result = _staging8
    _pos = _checkpoint31
    label ._end_discard12
    if not _mode:
        goto ._end_discard15
    _staging10 = _result
    _value12 = ')'
    _end12 = _pos + 1
    if _text[_pos:_end12] == _value12:
        _pos = _end12
        _checkpoint34 = _pos
        label ._loop_skip31
        _match56 = _pattern1.match(_text, _pos)
        if _match56:
            _pos = _match56.end()
            _mode = True
            _result = _match56.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint34 = _pos
            goto ._loop_skip31
        _match57 = _pattern2.match(_text, _pos)
        if _match57:
            _pos = _match57.end()
            _mode = True
            _result = _match57.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint34 = _pos
            goto ._loop_skip31
        _mode = True
        _result = None
        _pos = _checkpoint34
        _mode = True
        _result = _value12
    else:
        _mode = False
        _result = 139639492161888
    if _mode:
        _result = _staging10
    label ._end_discard15
    if not _mode:
        goto ._end_sequence7
    _item11 = _result
    _checkpoint35 = _pos
    label ._loop_skip32
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint35 = _pos
        goto ._loop_skip32
    _mode = True
    _result = None
    _pos = _checkpoint35
    if not _mode:
        goto ._end_discard16
    _backtrack6 = _pos
    _farthest_pos5 = _pos
    _farthest_expr5 = 139639492140000
    _value13 = '=>'
    _end13 = _pos + 2
    if _text[_pos:_end13] == _value13:
        _pos = _end13
        _checkpoint36 = _pos
        label ._loop_skip33
        _match58 = _pattern1.match(_text, _pos)
        if _match58:
            _pos = _match58.end()
            _mode = True
            _result = _match58.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint36 = _pos
            goto ._loop_skip33
        _match59 = _pattern2.match(_text, _pos)
        if _match59:
            _pos = _match59.end()
            _mode = True
            _result = _match59.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint36 = _pos
            goto ._loop_skip33
        _mode = True
        _result = None
        _pos = _checkpoint36
        _mode = True
        _result = _value13
    else:
        _mode = False
        _result = 139639492162896
    if _mode:
        goto ._end_choice5
    if _farthest_pos5 < _pos:
        _farthest_pos5 = _pos
        _farthest_expr5 = 139639492162896
    _pos = _backtrack6
    _value14 = '='
    _end14 = _pos + 1
    if _text[_pos:_end14] == _value14:
        _pos = _end14
        _checkpoint37 = _pos
        label ._loop_skip34
        _match60 = _pattern1.match(_text, _pos)
        if _match60:
            _pos = _match60.end()
            _mode = True
            _result = _match60.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint37 = _pos
            goto ._loop_skip34
        _match61 = _pattern2.match(_text, _pos)
        if _match61:
            _pos = _match61.end()
            _mode = True
            _result = _match61.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint37 = _pos
            goto ._loop_skip34
        _mode = True
        _result = None
        _pos = _checkpoint37
        _mode = True
        _result = _value14
    else:
        _mode = False
        _result = 139639492162952
    if _mode:
        goto ._end_choice5
    if _farthest_pos5 < _pos:
        _farthest_pos5 = _pos
        _farthest_expr5 = 139639492162952
    _pos = _backtrack6
    _value15 = ':'
    _end15 = _pos + 1
    if _text[_pos:_end15] == _value15:
        _pos = _end15
        _checkpoint38 = _pos
        label ._loop_skip35
        _match62 = _pattern1.match(_text, _pos)
        if _match62:
            _pos = _match62.end()
            _mode = True
            _result = _match62.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint38 = _pos
            goto ._loop_skip35
        _match63 = _pattern2.match(_text, _pos)
        if _match63:
            _pos = _match63.end()
            _mode = True
            _result = _match63.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint38 = _pos
            goto ._loop_skip35
        _mode = True
        _result = None
        _pos = _checkpoint38
        _mode = True
        _result = _value15
    else:
        _mode = False
        _result = 139639492162840
    if _mode:
        goto ._end_choice5
    if _farthest_pos5 < _pos:
        _farthest_pos5 = _pos
        _farthest_expr5 = 139639492162840
    _pos = _backtrack6
    _result = _farthest_expr5
    _pos = _farthest_pos5
    label ._end_choice5
    label ._end_discard16
    if not _mode:
        goto ._end_discard17
    _staging11 = _result
    _checkpoint39 = _pos
    label ._loop_skip36
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint39 = _pos
        goto ._loop_skip36
    _mode = True
    _result = None
    _pos = _checkpoint39
    if _mode:
        _result = _staging11
    label ._end_discard17
    if not _mode:
        goto ._end_discard18
    _mode, _result, _pos = yield (3, _parse_Expr1, _pos)
    label ._end_discard18
    if not _mode:
        goto ._end_sequence7
    _item12 = _result
    _result = TemplateDef(_item10, _item11, _item12)
    label ._end_sequence7
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Stmt1(_text, _pos):
    _backtrack7 = _pos
    _farthest_pos6 = _pos
    _farthest_expr6 = 139639492140448
    _mode, _result, _pos = yield (3, _parse_ClassDef1, _pos)
    if _mode:
        goto ._end_choice6
    if _farthest_pos6 < _pos:
        _farthest_pos6 = _pos
        _farthest_expr6 = 139639492163176
    _pos = _backtrack7
    _mode, _result, _pos = yield (3, _parse_TemplateDef1, _pos)
    if _mode:
        goto ._end_choice6
    if _farthest_pos6 < _pos:
        _farthest_pos6 = _pos
        _farthest_expr6 = 139639492163232
    _pos = _backtrack7
    _mode, _result, _pos = yield (3, _parse_RuleDef1, _pos)
    if _mode:
        goto ._end_choice6
    if _farthest_pos6 < _pos:
        _farthest_pos6 = _pos
        _farthest_expr6 = 139639492163120
    _pos = _backtrack7
    _mode, _result, _pos = yield (3, _parse_PythonSection1, _pos)
    if _mode:
        goto ._end_choice6
    if _farthest_pos6 < _pos:
        _farthest_pos6 = _pos
        _farthest_expr6 = 139639492163288
    _pos = _backtrack7
    _mode, _result, _pos = yield (3, _parse_PythonExpression1, _pos)
    if _mode:
        goto ._end_choice6
    if _farthest_pos6 < _pos:
        _farthest_pos6 = _pos
        _farthest_expr6 = 139639492163344
    _pos = _backtrack7
    _result = _farthest_expr6
    _pos = _farthest_pos6
    label ._end_choice6
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Ref1(_text, _pos):
    _mode, _result, _pos = yield (3, _parse_Name1, _pos)
    if not _mode:
        goto ._end_sequence8
    _item13 = _result
    _result = Ref(_item13)
    label ._end_sequence8
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_ListLiteral1(_text, _pos):
    _value16 = '['
    _end16 = _pos + 1
    if _text[_pos:_end16] == _value16:
        _pos = _end16
        _checkpoint40 = _pos
        label ._loop_skip37
        _match64 = _pattern1.match(_text, _pos)
        if _match64:
            _pos = _match64.end()
            _mode = True
            _result = _match64.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint40 = _pos
            goto ._loop_skip37
        _match65 = _pattern2.match(_text, _pos)
        if _match65:
            _pos = _match65.end()
            _mode = True
            _result = _match65.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint40 = _pos
            goto ._loop_skip37
        _mode = True
        _result = None
        _pos = _checkpoint40
        _mode = True
        _result = _value16
    else:
        _mode = False
        _result = 139639492163736
    if not _mode:
        goto ._end_discard19
    _staging12 = []
    _checkpoint41 = _pos
    label ._loop_alt3
    _checkpoint42 = _pos
    label ._loop_skip38
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint42 = _pos
        goto ._loop_skip38
    _mode = True
    _result = None
    _pos = _checkpoint42
    if not _mode:
        goto ._end_discard20
    _mode, _result, _pos = yield (3, _parse_Expr1, _pos)
    label ._end_discard20
    if not _mode:
        goto ._end_discard21
    _staging13 = _result
    _checkpoint43 = _pos
    label ._loop_skip39
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint43 = _pos
        goto ._loop_skip39
    _mode = True
    _result = None
    _pos = _checkpoint43
    if _mode:
        _result = _staging13
    label ._end_discard21
    if not _mode:
        goto ._end_alt3
    _staging12.append(_result)
    _checkpoint41 = _pos
    _mode, _result, _pos = yield (3, _parse_Comma1, _pos)
    if not _mode:
        goto ._end_alt3
    _checkpoint41 = _pos
    goto ._loop_alt3
    label ._end_alt3
    _mode = True
    _result = _staging12
    _pos = _checkpoint41
    label ._end_discard19
    if not _mode:
        goto ._end_discard22
    _staging14 = _result
    _value17 = ']'
    _end17 = _pos + 1
    if _text[_pos:_end17] == _value17:
        _pos = _end17
        _checkpoint44 = _pos
        label ._loop_skip40
        _match66 = _pattern1.match(_text, _pos)
        if _match66:
            _pos = _match66.end()
            _mode = True
            _result = _match66.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint44 = _pos
            goto ._loop_skip40
        _match67 = _pattern2.match(_text, _pos)
        if _match67:
            _pos = _match67.end()
            _mode = True
            _result = _match67.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint44 = _pos
            goto ._loop_skip40
        _mode = True
        _result = None
        _pos = _checkpoint44
        _mode = True
        _result = _value17
    else:
        _mode = False
        _result = 139639492163680
    if _mode:
        _result = _staging14
    label ._end_discard22
    if not _mode:
        goto ._end_sequence9
    _item14 = _result
    _result = ListLiteral(_item14)
    label ._end_sequence9
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Atom1(_text, _pos):
    _backtrack8 = _pos
    _farthest_pos7 = _pos
    _farthest_expr7 = 139639492141352
    _value18 = '('
    _end18 = _pos + 1
    if _text[_pos:_end18] == _value18:
        _pos = _end18
        _checkpoint45 = _pos
        label ._loop_skip41
        _match68 = _pattern1.match(_text, _pos)
        if _match68:
            _pos = _match68.end()
            _mode = True
            _result = _match68.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint45 = _pos
            goto ._loop_skip41
        _match69 = _pattern2.match(_text, _pos)
        if _match69:
            _pos = _match69.end()
            _mode = True
            _result = _match69.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint45 = _pos
            goto ._loop_skip41
        _mode = True
        _result = None
        _pos = _checkpoint45
        _mode = True
        _result = _value18
    else:
        _mode = False
        _result = 139639492164520
    if not _mode:
        goto ._end_discard23
    _checkpoint46 = _pos
    label ._loop_skip42
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint46 = _pos
        goto ._loop_skip42
    _mode = True
    _result = None
    _pos = _checkpoint46
    if not _mode:
        goto ._end_discard24
    _mode, _result, _pos = yield (3, _parse_Expr1, _pos)
    label ._end_discard24
    if not _mode:
        goto ._end_discard25
    _staging15 = _result
    _checkpoint47 = _pos
    label ._loop_skip43
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint47 = _pos
        goto ._loop_skip43
    _mode = True
    _result = None
    _pos = _checkpoint47
    if _mode:
        _result = _staging15
    label ._end_discard25
    label ._end_discard23
    if not _mode:
        goto ._end_discard26
    _staging16 = _result
    _value19 = ')'
    _end19 = _pos + 1
    if _text[_pos:_end19] == _value19:
        _pos = _end19
        _checkpoint48 = _pos
        label ._loop_skip44
        _match70 = _pattern1.match(_text, _pos)
        if _match70:
            _pos = _match70.end()
            _mode = True
            _result = _match70.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint48 = _pos
            goto ._loop_skip44
        _match71 = _pattern2.match(_text, _pos)
        if _match71:
            _pos = _match71.end()
            _mode = True
            _result = _match71.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint48 = _pos
            goto ._loop_skip44
        _mode = True
        _result = None
        _pos = _checkpoint48
        _mode = True
        _result = _value19
    else:
        _mode = False
        _result = 139639492164464
    if _mode:
        _result = _staging16
    label ._end_discard26
    if _mode:
        goto ._end_choice7
    if _farthest_pos7 < _pos:
        _farthest_pos7 = _pos
        _farthest_expr7 = 139639492141744
    _pos = _backtrack8
    _mode, _result, _pos = yield (3, _parse_Ref1, _pos)
    if _mode:
        goto ._end_choice7
    if _farthest_pos7 < _pos:
        _farthest_pos7 = _pos
        _farthest_expr7 = 139639492164408
    _pos = _backtrack8
    _mode, _result, _pos = yield (3, _parse_StringLiteral1, _pos)
    if _mode:
        goto ._end_choice7
    if _farthest_pos7 < _pos:
        _farthest_pos7 = _pos
        _farthest_expr7 = 139639492164352
    _pos = _backtrack8
    _mode, _result, _pos = yield (3, _parse_RegexLiteral1, _pos)
    if _mode:
        goto ._end_choice7
    if _farthest_pos7 < _pos:
        _farthest_pos7 = _pos
        _farthest_expr7 = 139639492164856
    _pos = _backtrack8
    _mode, _result, _pos = yield (3, _parse_ListLiteral1, _pos)
    if _mode:
        goto ._end_choice7
    if _farthest_pos7 < _pos:
        _farthest_pos7 = _pos
        _farthest_expr7 = 139639492164912
    _pos = _backtrack8
    _mode, _result, _pos = yield (3, _parse_PythonExpression1, _pos)
    if _mode:
        goto ._end_choice7
    if _farthest_pos7 < _pos:
        _farthest_pos7 = _pos
        _farthest_expr7 = 139639492164296
    _pos = _backtrack8
    _result = _farthest_expr7
    _pos = _farthest_pos7
    label ._end_choice7
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_KeywordArg1(_text, _pos):
    _mode, _result, _pos = yield (3, _parse_Name1, _pos)
    if not _mode:
        goto ._end_discard27
    _staging17 = _result
    _backtrack9 = _pos
    _farthest_pos8 = _pos
    _farthest_expr8 = 139639492141912
    _value20 = '='
    _end20 = _pos + 1
    if _text[_pos:_end20] == _value20:
        _pos = _end20
        _checkpoint49 = _pos
        label ._loop_skip45
        _match72 = _pattern1.match(_text, _pos)
        if _match72:
            _pos = _match72.end()
            _mode = True
            _result = _match72.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint49 = _pos
            goto ._loop_skip45
        _match73 = _pattern2.match(_text, _pos)
        if _match73:
            _pos = _match73.end()
            _mode = True
            _result = _match73.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint49 = _pos
            goto ._loop_skip45
        _mode = True
        _result = None
        _pos = _checkpoint49
        _mode = True
        _result = _value20
    else:
        _mode = False
        _result = 139639492165192
    if _mode:
        goto ._end_choice8
    if _farthest_pos8 < _pos:
        _farthest_pos8 = _pos
        _farthest_expr8 = 139639492165192
    _pos = _backtrack9
    _value21 = ':'
    _end21 = _pos + 1
    if _text[_pos:_end21] == _value21:
        _pos = _end21
        _checkpoint50 = _pos
        label ._loop_skip46
        _match74 = _pattern1.match(_text, _pos)
        if _match74:
            _pos = _match74.end()
            _mode = True
            _result = _match74.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint50 = _pos
            goto ._loop_skip46
        _match75 = _pattern2.match(_text, _pos)
        if _match75:
            _pos = _match75.end()
            _mode = True
            _result = _match75.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint50 = _pos
            goto ._loop_skip46
        _mode = True
        _result = None
        _pos = _checkpoint50
        _mode = True
        _result = _value21
    else:
        _mode = False
        _result = 139639492165248
    if _mode:
        goto ._end_choice8
    if _farthest_pos8 < _pos:
        _farthest_pos8 = _pos
        _farthest_expr8 = 139639492165248
    _pos = _backtrack9
    _result = _farthest_expr8
    _pos = _farthest_pos8
    label ._end_choice8
    if _mode:
        _result = _staging17
    label ._end_discard27
    if not _mode:
        goto ._end_sequence10
    _item15 = _result
    _mode, _result, _pos = yield (3, _parse_Expr1, _pos)
    if not _mode:
        goto ._end_sequence10
    _item16 = _result
    _result = KeywordArg(_item15, _item16)
    label ._end_sequence10
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_ArgList1(_text, _pos):
    _value22 = '('
    _end22 = _pos + 1
    if _text[_pos:_end22] == _value22:
        _pos = _end22
        _checkpoint51 = _pos
        label ._loop_skip47
        _match76 = _pattern1.match(_text, _pos)
        if _match76:
            _pos = _match76.end()
            _mode = True
            _result = _match76.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint51 = _pos
            goto ._loop_skip47
        _match77 = _pattern2.match(_text, _pos)
        if _match77:
            _pos = _match77.end()
            _mode = True
            _result = _match77.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint51 = _pos
            goto ._loop_skip47
        _mode = True
        _result = None
        _pos = _checkpoint51
        _mode = True
        _result = _value22
    else:
        _mode = False
        _result = 139639492124744
    if not _mode:
        goto ._end_discard28
    _staging18 = []
    _checkpoint52 = _pos
    label ._loop_alt4
    _checkpoint53 = _pos
    label ._loop_skip48
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint53 = _pos
        goto ._loop_skip48
    _mode = True
    _result = None
    _pos = _checkpoint53
    if not _mode:
        goto ._end_discard29
    _backtrack10 = _pos
    _farthest_pos9 = _pos
    _farthest_expr9 = 139639492142248
    _mode, _result, _pos = yield (3, _parse_KeywordArg1, _pos)
    if _mode:
        goto ._end_choice9
    if _farthest_pos9 < _pos:
        _farthest_pos9 = _pos
        _farthest_expr9 = 139639492125136
    _pos = _backtrack10
    _mode, _result, _pos = yield (3, _parse_Expr1, _pos)
    if _mode:
        goto ._end_choice9
    if _farthest_pos9 < _pos:
        _farthest_pos9 = _pos
        _farthest_expr9 = 139639492125192
    _pos = _backtrack10
    _result = _farthest_expr9
    _pos = _farthest_pos9
    label ._end_choice9
    label ._end_discard29
    if not _mode:
        goto ._end_discard30
    _staging19 = _result
    _checkpoint54 = _pos
    label ._loop_skip49
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint54 = _pos
        goto ._loop_skip49
    _mode = True
    _result = None
    _pos = _checkpoint54
    if _mode:
        _result = _staging19
    label ._end_discard30
    if not _mode:
        goto ._end_alt4
    _staging18.append(_result)
    _checkpoint52 = _pos
    _mode, _result, _pos = yield (3, _parse_Comma1, _pos)
    if not _mode:
        goto ._end_alt4
    _checkpoint52 = _pos
    goto ._loop_alt4
    label ._end_alt4
    _mode = True
    _result = _staging18
    _pos = _checkpoint52
    label ._end_discard28
    if not _mode:
        goto ._end_discard31
    _staging20 = _result
    _value23 = ')'
    _end23 = _pos + 1
    if _text[_pos:_end23] == _value23:
        _pos = _end23
        _checkpoint55 = _pos
        label ._loop_skip50
        _match78 = _pattern1.match(_text, _pos)
        if _match78:
            _pos = _match78.end()
            _mode = True
            _result = _match78.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint55 = _pos
            goto ._loop_skip50
        _match79 = _pattern2.match(_text, _pos)
        if _match79:
            _pos = _match79.end()
            _mode = True
            _result = _match79.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint55 = _pos
            goto ._loop_skip50
        _mode = True
        _result = None
        _pos = _checkpoint55
        _mode = True
        _result = _value23
    else:
        _mode = False
        _result = 139639492165584
    if _mode:
        _result = _staging20
    label ._end_discard31
    if not _mode:
        goto ._end_sequence11
    _item17 = _result
    _result = ArgList(_item17)
    label ._end_sequence11
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_Expr1(_text, _pos):
    _staging21 = None
    _checkpoint56 = _pos
    _is_first1 = True
    goto ._left_assoc_operand1
    label ._loop_left_assoc1
    _checkpoint57 = _pos
    label ._loop_skip51
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint57 = _pos
        goto ._loop_skip51
    _mode = True
    _result = None
    _pos = _checkpoint57
    if not _mode:
        goto ._end_discard32
    _value24 = '|'
    _end24 = _pos + 1
    if _text[_pos:_end24] == _value24:
        _pos = _end24
        _checkpoint58 = _pos
        label ._loop_skip52
        _match80 = _pattern1.match(_text, _pos)
        if _match80:
            _pos = _match80.end()
            _mode = True
            _result = _match80.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint58 = _pos
            goto ._loop_skip52
        _match81 = _pattern2.match(_text, _pos)
        if _match81:
            _pos = _match81.end()
            _mode = True
            _result = _match81.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint58 = _pos
            goto ._loop_skip52
        _mode = True
        _result = None
        _pos = _checkpoint58
        _mode = True
        _result = _value24
    else:
        _mode = False
        _result = 139639492127432
    label ._end_discard32
    if not _mode:
        goto ._end_discard33
    _staging22 = _result
    _checkpoint59 = _pos
    label ._loop_skip53
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint59 = _pos
        goto ._loop_skip53
    _mode = True
    _result = None
    _pos = _checkpoint59
    if _mode:
        _result = _staging22
    label ._end_discard33
    if not _mode:
        goto ._suceed_left_assoc1
    _operator1 = _result
    label ._left_assoc_operand1
    _staging23 = None
    _checkpoint60 = _pos
    _is_first2 = True
    goto ._left_assoc_operand2
    label ._loop_left_assoc2
    _checkpoint61 = _pos
    label ._loop_skip54
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint61 = _pos
        goto ._loop_skip54
    _mode = True
    _result = None
    _pos = _checkpoint61
    if not _mode:
        goto ._end_discard34
    _backtrack11 = _pos
    _farthest_pos10 = _pos
    _farthest_expr10 = 139639492143648
    _value25 = '<|'
    _end25 = _pos + 2
    if _text[_pos:_end25] == _value25:
        _pos = _end25
        _checkpoint62 = _pos
        label ._loop_skip55
        _match82 = _pattern1.match(_text, _pos)
        if _match82:
            _pos = _match82.end()
            _mode = True
            _result = _match82.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint62 = _pos
            goto ._loop_skip55
        _match83 = _pattern2.match(_text, _pos)
        if _match83:
            _pos = _match83.end()
            _mode = True
            _result = _match83.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint62 = _pos
            goto ._loop_skip55
        _mode = True
        _result = None
        _pos = _checkpoint62
        _mode = True
        _result = _value25
    else:
        _mode = False
        _result = 139639492127152
    if _mode:
        goto ._end_choice10
    if _farthest_pos10 < _pos:
        _farthest_pos10 = _pos
        _farthest_expr10 = 139639492127152
    _pos = _backtrack11
    _value26 = '|>'
    _end26 = _pos + 2
    if _text[_pos:_end26] == _value26:
        _pos = _end26
        _checkpoint63 = _pos
        label ._loop_skip56
        _match84 = _pattern1.match(_text, _pos)
        if _match84:
            _pos = _match84.end()
            _mode = True
            _result = _match84.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint63 = _pos
            goto ._loop_skip56
        _match85 = _pattern2.match(_text, _pos)
        if _match85:
            _pos = _match85.end()
            _mode = True
            _result = _match85.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint63 = _pos
            goto ._loop_skip56
        _mode = True
        _result = None
        _pos = _checkpoint63
        _mode = True
        _result = _value26
    else:
        _mode = False
        _result = 139639492127208
    if _mode:
        goto ._end_choice10
    if _farthest_pos10 < _pos:
        _farthest_pos10 = _pos
        _farthest_expr10 = 139639492127208
    _pos = _backtrack11
    _value27 = 'where'
    _end27 = _pos + 5
    if _text[_pos:_end27] == _value27:
        _pos = _end27
        _checkpoint64 = _pos
        label ._loop_skip57
        _match86 = _pattern1.match(_text, _pos)
        if _match86:
            _pos = _match86.end()
            _mode = True
            _result = _match86.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint64 = _pos
            goto ._loop_skip57
        _match87 = _pattern2.match(_text, _pos)
        if _match87:
            _pos = _match87.end()
            _mode = True
            _result = _match87.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint64 = _pos
            goto ._loop_skip57
        _mode = True
        _result = None
        _pos = _checkpoint64
        _mode = True
        _result = _value27
    else:
        _mode = False
        _result = 139639492127096
    if _mode:
        goto ._end_choice10
    if _farthest_pos10 < _pos:
        _farthest_pos10 = _pos
        _farthest_expr10 = 139639492127096
    _pos = _backtrack11
    _result = _farthest_expr10
    _pos = _farthest_pos10
    label ._end_choice10
    label ._end_discard34
    if not _mode:
        goto ._end_discard35
    _staging24 = _result
    _checkpoint65 = _pos
    label ._loop_skip58
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint65 = _pos
        goto ._loop_skip58
    _mode = True
    _result = None
    _pos = _checkpoint65
    if _mode:
        _result = _staging24
    label ._end_discard35
    if not _mode:
        goto ._suceed_left_assoc2
    _operator2 = _result
    label ._left_assoc_operand2
    _staging25 = None
    _checkpoint66 = _pos
    _is_first3 = True
    goto ._left_assoc_operand3
    label ._loop_left_assoc3
    _checkpoint67 = _pos
    label ._loop_skip59
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint67 = _pos
        goto ._loop_skip59
    _mode = True
    _result = None
    _pos = _checkpoint67
    if not _mode:
        goto ._end_discard36
    _backtrack12 = _pos
    _farthest_pos11 = _pos
    _farthest_expr11 = 139639492143312
    _value28 = '<<'
    _end28 = _pos + 2
    if _text[_pos:_end28] == _value28:
        _pos = _end28
        _checkpoint68 = _pos
        label ._loop_skip60
        _match88 = _pattern1.match(_text, _pos)
        if _match88:
            _pos = _match88.end()
            _mode = True
            _result = _match88.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint68 = _pos
            goto ._loop_skip60
        _match89 = _pattern2.match(_text, _pos)
        if _match89:
            _pos = _match89.end()
            _mode = True
            _result = _match89.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint68 = _pos
            goto ._loop_skip60
        _mode = True
        _result = None
        _pos = _checkpoint68
        _mode = True
        _result = _value28
    else:
        _mode = False
        _result = 139639492126760
    if _mode:
        goto ._end_choice11
    if _farthest_pos11 < _pos:
        _farthest_pos11 = _pos
        _farthest_expr11 = 139639492126760
    _pos = _backtrack12
    _value29 = '>>'
    _end29 = _pos + 2
    if _text[_pos:_end29] == _value29:
        _pos = _end29
        _checkpoint69 = _pos
        label ._loop_skip61
        _match90 = _pattern1.match(_text, _pos)
        if _match90:
            _pos = _match90.end()
            _mode = True
            _result = _match90.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint69 = _pos
            goto ._loop_skip61
        _match91 = _pattern2.match(_text, _pos)
        if _match91:
            _pos = _match91.end()
            _mode = True
            _result = _match91.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint69 = _pos
            goto ._loop_skip61
        _mode = True
        _result = None
        _pos = _checkpoint69
        _mode = True
        _result = _value29
    else:
        _mode = False
        _result = 139639492126816
    if _mode:
        goto ._end_choice11
    if _farthest_pos11 < _pos:
        _farthest_pos11 = _pos
        _farthest_expr11 = 139639492126816
    _pos = _backtrack12
    _result = _farthest_expr11
    _pos = _farthest_pos11
    label ._end_choice11
    label ._end_discard36
    if not _mode:
        goto ._end_discard37
    _staging26 = _result
    _checkpoint70 = _pos
    label ._loop_skip62
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint70 = _pos
        goto ._loop_skip62
    _mode = True
    _result = None
    _pos = _checkpoint70
    if _mode:
        _result = _staging26
    label ._end_discard37
    if not _mode:
        goto ._suceed_left_assoc3
    _operator3 = _result
    label ._left_assoc_operand3
    _staging27 = None
    _checkpoint71 = _pos
    _is_first4 = True
    goto ._left_assoc_operand4
    label ._loop_left_assoc4
    _checkpoint72 = _pos
    label ._loop_skip63
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint72 = _pos
        goto ._loop_skip63
    _mode = True
    _result = None
    _pos = _checkpoint72
    if not _mode:
        goto ._end_discard38
    _backtrack13 = _pos
    _farthest_pos12 = _pos
    _farthest_expr12 = 139639492142976
    _value30 = '//'
    _end30 = _pos + 2
    if _text[_pos:_end30] == _value30:
        _pos = _end30
        _checkpoint73 = _pos
        label ._loop_skip64
        _match92 = _pattern1.match(_text, _pos)
        if _match92:
            _pos = _match92.end()
            _mode = True
            _result = _match92.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint73 = _pos
            goto ._loop_skip64
        _match93 = _pattern2.match(_text, _pos)
        if _match93:
            _pos = _match93.end()
            _mode = True
            _result = _match93.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint73 = _pos
            goto ._loop_skip64
        _mode = True
        _result = None
        _pos = _checkpoint73
        _mode = True
        _result = _value30
    else:
        _mode = False
        _result = 139639492126424
    if _mode:
        goto ._end_choice12
    if _farthest_pos12 < _pos:
        _farthest_pos12 = _pos
        _farthest_expr12 = 139639492126424
    _pos = _backtrack13
    _value31 = '/'
    _end31 = _pos + 1
    if _text[_pos:_end31] == _value31:
        _pos = _end31
        _checkpoint74 = _pos
        label ._loop_skip65
        _match94 = _pattern1.match(_text, _pos)
        if _match94:
            _pos = _match94.end()
            _mode = True
            _result = _match94.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint74 = _pos
            goto ._loop_skip65
        _match95 = _pattern2.match(_text, _pos)
        if _match95:
            _pos = _match95.end()
            _mode = True
            _result = _match95.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint74 = _pos
            goto ._loop_skip65
        _mode = True
        _result = None
        _pos = _checkpoint74
        _mode = True
        _result = _value31
    else:
        _mode = False
        _result = 139639492126480
    if _mode:
        goto ._end_choice12
    if _farthest_pos12 < _pos:
        _farthest_pos12 = _pos
        _farthest_expr12 = 139639492126480
    _pos = _backtrack13
    _result = _farthest_expr12
    _pos = _farthest_pos12
    label ._end_choice12
    label ._end_discard38
    if not _mode:
        goto ._end_discard39
    _staging28 = _result
    _checkpoint75 = _pos
    label ._loop_skip66
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint75 = _pos
        goto ._loop_skip66
    _mode = True
    _result = None
    _pos = _checkpoint75
    if _mode:
        _result = _staging28
    label ._end_discard39
    if not _mode:
        goto ._suceed_left_assoc4
    _operator4 = _result
    label ._left_assoc_operand4
    _mode, _result, _pos = yield (3, _parse_Atom1, _pos)
    if not _mode:
        goto ._end_postfix1
    _staging29 = _result
    _checkpoint76 = _pos
    label ._loop_postfix1
    _mode, _result, _pos = yield (3, _parse_ArgList1, _pos)
    if _mode:
        _staging29 = Postfix(_staging29, _result)
        _checkpoint76 = _pos
        goto ._loop_postfix1
    else:
        _mode = True
        _result = _staging29
        _pos = _checkpoint76
    label ._end_postfix1
    if not _mode:
        goto ._end_postfix2
    _staging30 = _result
    _checkpoint77 = _pos
    label ._loop_postfix2
    _backtrack14 = _pos
    _farthest_pos13 = _pos
    _farthest_expr13 = 139639492142808
    _value32 = '?'
    _end32 = _pos + 1
    if _text[_pos:_end32] == _value32:
        _pos = _end32
        _checkpoint78 = _pos
        label ._loop_skip67
        _match96 = _pattern1.match(_text, _pos)
        if _match96:
            _pos = _match96.end()
            _mode = True
            _result = _match96.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint78 = _pos
            goto ._loop_skip67
        _match97 = _pattern2.match(_text, _pos)
        if _match97:
            _pos = _match97.end()
            _mode = True
            _result = _match97.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint78 = _pos
            goto ._loop_skip67
        _mode = True
        _result = None
        _pos = _checkpoint78
        _mode = True
        _result = _value32
    else:
        _mode = False
        _result = 139639492125976
    if _mode:
        goto ._end_choice13
    if _farthest_pos13 < _pos:
        _farthest_pos13 = _pos
        _farthest_expr13 = 139639492125976
    _pos = _backtrack14
    _value33 = '*'
    _end33 = _pos + 1
    if _text[_pos:_end33] == _value33:
        _pos = _end33
        _checkpoint79 = _pos
        label ._loop_skip68
        _match98 = _pattern1.match(_text, _pos)
        if _match98:
            _pos = _match98.end()
            _mode = True
            _result = _match98.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint79 = _pos
            goto ._loop_skip68
        _match99 = _pattern2.match(_text, _pos)
        if _match99:
            _pos = _match99.end()
            _mode = True
            _result = _match99.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint79 = _pos
            goto ._loop_skip68
        _mode = True
        _result = None
        _pos = _checkpoint79
        _mode = True
        _result = _value33
    else:
        _mode = False
        _result = 139639492126032
    if _mode:
        goto ._end_choice13
    if _farthest_pos13 < _pos:
        _farthest_pos13 = _pos
        _farthest_expr13 = 139639492126032
    _pos = _backtrack14
    _value34 = '+'
    _end34 = _pos + 1
    if _text[_pos:_end34] == _value34:
        _pos = _end34
        _checkpoint80 = _pos
        label ._loop_skip69
        _match100 = _pattern1.match(_text, _pos)
        if _match100:
            _pos = _match100.end()
            _mode = True
            _result = _match100.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint80 = _pos
            goto ._loop_skip69
        _match101 = _pattern2.match(_text, _pos)
        if _match101:
            _pos = _match101.end()
            _mode = True
            _result = _match101.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint80 = _pos
            goto ._loop_skip69
        _mode = True
        _result = None
        _pos = _checkpoint80
        _mode = True
        _result = _value34
    else:
        _mode = False
        _result = 139639492125920
    if _mode:
        goto ._end_choice13
    if _farthest_pos13 < _pos:
        _farthest_pos13 = _pos
        _farthest_expr13 = 139639492125920
    _pos = _backtrack14
    _result = _farthest_expr13
    _pos = _farthest_pos13
    label ._end_choice13
    if _mode:
        _staging30 = Postfix(_staging30, _result)
        _checkpoint77 = _pos
        goto ._loop_postfix2
    else:
        _mode = True
        _result = _staging30
        _pos = _checkpoint77
    label ._end_postfix2
    if not _mode:
        if _is_first4:
            goto ._end_left_assoc4
        else:
            goto ._suceed_left_assoc4
    _checkpoint71 = _pos
    if _is_first4:
        _is_first4 = False
        _staging27 = _result
    else:
        _staging27 = Infix(_staging27, _operator4, _result)
    goto ._loop_left_assoc4
    label ._suceed_left_assoc4
    _mode = True
    _result = _staging27
    _pos = _checkpoint71
    label ._end_left_assoc4
    if not _mode:
        if _is_first3:
            goto ._end_left_assoc3
        else:
            goto ._suceed_left_assoc3
    _checkpoint66 = _pos
    if _is_first3:
        _is_first3 = False
        _staging25 = _result
    else:
        _staging25 = Infix(_staging25, _operator3, _result)
    goto ._loop_left_assoc3
    label ._suceed_left_assoc3
    _mode = True
    _result = _staging25
    _pos = _checkpoint66
    label ._end_left_assoc3
    if not _mode:
        if _is_first2:
            goto ._end_left_assoc2
        else:
            goto ._suceed_left_assoc2
    _checkpoint60 = _pos
    if _is_first2:
        _is_first2 = False
        _staging23 = _result
    else:
        _staging23 = Infix(_staging23, _operator2, _result)
    goto ._loop_left_assoc2
    label ._suceed_left_assoc2
    _mode = True
    _result = _staging23
    _pos = _checkpoint60
    label ._end_left_assoc2
    if not _mode:
        if _is_first1:
            goto ._end_left_assoc1
        else:
            goto ._suceed_left_assoc1
    _checkpoint56 = _pos
    if _is_first1:
        _is_first1 = False
        _staging21 = _result
    else:
        _staging21 = Infix(_staging21, _operator1, _result)
    goto ._loop_left_assoc1
    label ._suceed_left_assoc1
    _mode = True
    _result = _staging21
    _pos = _checkpoint56
    label ._end_left_assoc1
    yield (_mode, _result, _pos)
    

@with_goto
def _parse_start1(_text, _pos):
    _checkpoint81 = _pos
    label ._loop_skip70
    _mode, _result, _pos = yield (3, _parse_Newline1, _pos)
    if _mode:
        _checkpoint81 = _pos
        goto ._loop_skip70
    _mode = True
    _result = None
    _pos = _checkpoint81
    if not _mode:
        goto ._end_discard40
    _staging31 = []
    _checkpoint82 = _pos
    label ._loop_alt5
    _mode, _result, _pos = yield (3, _parse_Stmt1, _pos)
    if not _mode:
        goto ._end_alt5
    _staging31.append(_result)
    _checkpoint82 = _pos
    _mode, _result, _pos = yield (3, _parse_Sep1, _pos)
    if not _mode:
        goto ._end_alt5
    _checkpoint82 = _pos
    goto ._loop_alt5
    label ._end_alt5
    _mode = True
    _result = _staging31
    _pos = _checkpoint82
    label ._end_discard40
    yield (_mode, _result, _pos)
    

@with_goto
def _skip_then_start(_text, _pos):
    _checkpoint83 = _pos
    label ._loop_skip71
    _match102 = _pattern1.match(_text, _pos)
    if _match102:
        _pos = _match102.end()
        _checkpoint84 = _pos
        label ._loop_skip72
        _match103 = _pattern1.match(_text, _pos)
        if _match103:
            _pos = _match103.end()
            _mode = True
            _result = _match103.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint84 = _pos
            goto ._loop_skip72
        _match104 = _pattern2.match(_text, _pos)
        if _match104:
            _pos = _match104.end()
            _mode = True
            _result = _match104.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint84 = _pos
            goto ._loop_skip72
        _mode = True
        _result = None
        _pos = _checkpoint84
        _mode = True
        _result = _match102.group(0)
    else:
        _mode = False
        _result = 139639492039624
    if _mode:
        _checkpoint83 = _pos
        goto ._loop_skip71
    _match105 = _pattern2.match(_text, _pos)
    if _match105:
        _pos = _match105.end()
        _checkpoint85 = _pos
        label ._loop_skip73
        _match106 = _pattern1.match(_text, _pos)
        if _match106:
            _pos = _match106.end()
            _mode = True
            _result = _match106.group(0)
        else:
            _mode = False
            _result = 139639492039624
        if _mode:
            _checkpoint85 = _pos
            goto ._loop_skip73
        _match107 = _pattern2.match(_text, _pos)
        if _match107:
            _pos = _match107.end()
            _mode = True
            _result = _match107.group(0)
        else:
            _mode = False
            _result = 139639492005280
        if _mode:
            _checkpoint85 = _pos
            goto ._loop_skip73
        _mode = True
        _result = None
        _pos = _checkpoint85
        _mode = True
        _result = _match105.group(0)
    else:
        _mode = False
        _result = 139639492005280
    if _mode:
        _checkpoint83 = _pos
        goto ._loop_skip71
    _mode = True
    _result = None
    _pos = _checkpoint83
    if not _mode:
        goto ._end_discard41
    _mode, _result, _pos = yield (3, _parse_start1, _pos)
    label ._end_discard41
    yield (_mode, _result, _pos)
    
